dist: xenial
language: cpp
script: cmake . && make
deploy:
  'on':
    branch: master
  provider: script
  script: docker run -v $(pwd):$(pwd) -t snapcore/snapcraft sh -c "apt update -qq
    && cd $(pwd) && snapcraft "
  skip_cleanup: true
after_success:
- openssl aes-256-cbc -K $encrypted_4ce617354043_key -iv $encrypted_4ce617354043_iv
  -in .snapcraft/travis_snapcraft.cfg -out .snapcraft/snapcraft.cfg -d
  - snapcraft login --with .snapcraft/snapcraft.cfg
  - snapcraft push *.snap --release edge
sudo: required
services:
- docker
