dist: xenial
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
before_script:
  - export  CC='gcc-8' CXX='g++-8' TRAVIS_COMPILER='g++-8' CXX_FOR_BUILD='g++-8'
script: cmake . && make
after_success:
- openssl aes-256-cbc -K $encrypted_4ce617354043_key -iv $encrypted_4ce617354043_iv
  -in .snapcraft/travis_snapcraft.cfg -out .snapcraft/snapcraft.cfg -d
sudo: required
services:
- docker
deploy:
  'on':
    branch: master
  provider: script
  script: docker run -v $(pwd):$(pwd) -t snapcore/snapcraft sh -c "
    sudo apt-get install software-properties-common && 
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test &&
    sudo apt-get update &&
    cd $(pwd) && sudo apt-get install g++-8 gcc-8 && export  CC='gcc-8' CXX='g++-8' TRAVIS_COMPILER='g++-8' CXX_FOR_BUILD='g++-8' && snapcraft && snapcraft push *.snap --release edge"
  skip_cleanup: true
