version: 1.0.{build}
image: Visual Studio 2015
install: 
  - set PATH=%PATH%;%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin
  - set CC=C:\Qt\Tools\mingw530_32\bin\gcc.exe
  - set CXX=C:\Qt\Tools\mingw530_32\bin\g++.exe
  - set Qt5_DIR=%QTDIR%\lib\cmake\Qt5
  - set PATH=%PATH:C:\Program Files\Git\usr\bin=% # trick to remove sh.exe
before_build:
    - cmake -DCMAKE_BUILD_TYPE=Debug -G"CodeBlocks - MinGW Makefiles" .
build_script:
  - mingw32-make
artifacts:
    path: bin
    name: oop-exercises
deploy:
  release: oop-exercises-v$(appveyor_build_version)
  description: 'OOP Exercises for C++ students'
  provider: GitHub
  auth_token:
    secure: cD3DTUOZ5cJfsjkCsg+eHyLaijR4wf+FwrDE7LTNQIEdeLF0HcU9hgmxxUcGxB2Y # your encrypted token from GitHub
  artifact: /oop-exercises         
  draft: false
  prerelease: false
  on:
    branch: master                 
    APPVEYOR_REPO_TAG: true 