version: 1.1.{build}
image: Visual Studio 2015
install: 
  - set PATH=%PATH:C:\Program Files\Git\usr\bin=% # trick to remove sh.exe
  - set PATH=%PATH%;C:\cygwin64\bin;C:\MinGW\bin
  - set CC=C:\cygwin64\bin\gcc.exe
  - set CXX=C:\cygwin64\bin\g++.exe
before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_SH="CMAKE_SH-NOTFOUND" -G"CodeBlocks - MinGW Makefiles" .
build_script:
  - mingw32-make
after_build:
  - xcopy /s exercises bin\exercises\
  - copy mingw-to-path.bat bin\
  - xcopy /s answers bin\answers\

artifacts:
  - path: bin/
    name: oop-exercises

deploy:
  - provider: GitHub
    artifacts: oop-exercises
    auth_token:
      secure: aIiYr0MeanCLsD/pLbbRO0XtDuSTpRor3ABjJMGPqjvlmLDvAl49TG5VtphFXSnF
