version: 1.1.{build}
image: Visual Studio 2015
install: 
  - choco install mingw
  - choco install codeblocks
  - set PATH=%PATH%;C:\MinGW\bin
  - set CC=C:\MinGW\bin\gcc.exe
  - set CXX=C:\MinGW\bin\g++.exe
  - set PATH=%PATH:C:\Program Files\Git\usr\bin=% # trick to remove sh.exe
before_build:
    - cmake -DCMAKE_BUILD_TYPE=Debug -G"CodeBlocks - MinGW Makefiles" .
build_script:
  - mingw32-make
after_build:
  - xcopy /s exercises bin\exercises\
  - copy mingw-to-path.bat bin\
  - xcopy /s answers bin\answers\

artifacts:
    - path: bin/
      name: oop-exercises

deploy:
- provider: GitHub
  auth_token:
    secure: aIiYr0MeanCLsD/pLbbRO0XtDuSTpRor3ABjJMGPqjvlmLDvAl49TG5VtphFXSnF
