version: 1.0.{build}
image: Visual Studio 2015
install: C:\MinGW\bin\mingw32-g++.exe --version && C:\MinGW\bin\mingw32-g++.exe check.cpp -o bin/checker && C:\MinGW\bin\mingw32-g++.exe create-question.cpp -o bin/create-question && echo "DONE"
artifacts:
    path: bin
    name: myApp 
