version: 1.1.{build}
image: Visual Studio 2017
install: 
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
before_build:
  - cmake .
build_script:
  - dir
  - msbuild ALL_BUILD.vcxproj /std:c++latest
after_build:
  - xcopy /s exercises bin\exercises\
  - copy mingw-to-path.bat bin\
  - xcopy /s answers bin\answers\

artifacts:
  - path: bin/
    name: oop-exercises

deploy:
  - provider: GitHub
    artifacts: oop-exercises
    auth_token:
      secure: aIiYr0MeanCLsD/pLbbRO0XtDuSTpRor3ABjJMGPqjvlmLDvAl49TG5VtphFXSnF
