version: 1.2.{build}
image: Visual Studio 2015
install: 
  - set PATH=%PATH%;%QTDIR%\bin;C:\Mingw\bin
  - set CC=C:\Mingw\bin\gcc.exe
  - set CXX=C:\Mingw\bin\g++.exe
  - set PATH=%PATH:C:\Program Files\Git\usr\bin=% # trick to remove sh.exe
before_build:
  - cmake -DCMAKE_BUILD_TYPE=Debug -G"CodeBlocks - MinGW Makefiles" .
build_script:
  - mingw32-make
artifacts:
    path: bin
    name: myApp 
