name: oop-exercises
version: 0.1.1
summary: OOP Exercises in C++
description: Exercises for those who to learn Object-Oriented Programming in C++
grade: devel
confinement: devmode

apps:
  check:
    command: bin/check
  
  create-exercise:
    command: bin/create-exercise

parts:
  app:
    source: .
    plugin: cmake
    stage-packages: [gcc, g++, libc6] # needed inside the container



  
