name: oop-exercises
version: git
summary: OOP Exercises in C++
description: Exercises for those who to learn Object-Oriented Programming in C++
grade: stable
confinement: devmode

apps:
  check:
    command: bin/check
    plugs: [personal-files]

  create-exercise:
    command: bin/create-exercise
    plugs: [personal-files]

parts:
  app:
    source: https://github.com/kerolloz/oop-exercises.git
    plugin: cmake
    stage-packages: [g++] # needed inside the container
