name: oop-exercises
version: 0.1.1
summary: OOP Exercises in C++
description: Exercises for those who to learn Object-Oriented Programming in C++
grade: devel
confinement: devmode

apps:
  check:
    command: bin/check
    stop-timeout: 2s
  
  create-exercise:
    command: bin/create-exercise
    stop-timeout: 2s

parts:
  app:
    source: https://github.com/kerolloz/oop-exercises.git
    plugin: cmake
    stage-packages: [gcc, g++, libc6]


  